import requests
import sys
import os

print("IServ Task Downloader v0.0.6 by JonaRL")

#Benutzerdaten auslesen
try:
  usrdata = open(open(os.path.abspath(__file__)).read().split("#df:")[3].split(";")[0] + "user.data").read()
  server = usrdata.split("server:")[1].split(";")[0]
  username = usrdata.split("username:")[1].split(";")[0]
  password = usrdata.split("password:")[1].split(";")[0]
  index = usrdata.split("index:")[1].split(";")[0]
  datafolder = usrdata.split("datafolder:")[1].split(";")[0]
  taskfilter = usrdata.split("taskfilter:")[1].split(";")[0]
except:
  #Einrichtungsassistenten starten
  print("Willkommen bei ITask! Dieser Einrichtungsassistent wird dir helfen, das Programm zu konfigurieren.")
  print("Als erstes starten wir mit einigen Angaben zu deinem IServ-Profil.")
  print("1. Wie lautet die Domain deines IServ-Servers? Beispiel: demo-iserv.de")
  server = input("Eingabe: ")
  print("2. Wie lautet dein IServ-Benutzername? Beispiel: user.name")
  username = input("Eingabe: ")
  print("3. Wie lautet dein Passwort? Beispiel: 5h(k+asdf37")
  password = input("Eingabe: ")
  print("Super! Nun lediglich noch ein paar Angaben dazu, wo und wie ITask seine Daten speichern soll, und du kannst loslegen.")
  print("4. Wo soll deine Index-Datei liegen? Über diese Datei wirst du auf die Aufgaben zugreifen können, platziere sie also an einem Ort, den du findest. Beispiel: /home/user/ITask.html")
  index = input("Eingabe: ")
  print("5. Gib nun an, wo ITask die Aufgaben und dazugehörige Dateien speichern soll. Wähle am besten einen versteckten Ordner, ITask ist nämlich ziemlich unordentlich :) Beispiel: /home/user/.itask")
  datafolder = input("Eingabe: ")
  print("6. Als letztes solltest du noch festlegen, welche Aufgaben heruntergeladen werden sollen. Wenn du dieses Feld nicht ausfüllst, werden immer alle aktuellen Aufgaben geladen.")
  print("Die möglichen Werte lauten: current, past oder all.")
  taskfilter = input("Eingabe: ")

  #Variablen optimieren
  if taskfilter != "current" and taskfilter != "past" and taskfilter != "all":
    taskfilter = "current"
  if index[-1] == "/":
    index = index[:-1]
  if index.find(".html") == -1:
    index = index + ".html"
  if datafolder[-1] != "/":
    datafolder = datafolder + "/"
  if os.path.isdir(datafolder) == False:
    os.mkdir(datafolder)

  #Nutzer um Bestätigung bitten
  print("Möchtest du diese Nutzerdaten speichern?")
  print("IServ-Domain: " + server)
  print("Benutzername: " + username)
  print("Passwort: " + password)
  print("ITask-Datei: " + index)
  print("ITask-Datenordner: " + datafolder)
  print("Filter: " + taskfilter)
  print("Möchtest du diese Einstellungen speichern? Bitte gebe 'Ja' oder 'Nein' ein")
  if input("Eingabe: ") != "Ja":
    sys.exit(0)

  #Daten schreiben
  with open(datafolder + "user.data", "a") as f:
    f.write("Generated by ITask Version 0.0.6\nserver:" + server + ";\nusername:" + username + ";\npassword:" + password + ";\nindex:" + index + ";datafolder:" + datafolder + ";taskfilter:" + taskfilter + ";")
  with open(os.path.abspath(__file__), "a") as f:
    f.write("\n#df:" + datafolder + ";")

#Variablen definieren
url1 = "<td class=\"iserv-admin-list-field iserv-admin-list-field-textarea\"><a href=\""
url2 = "\">"
name = "</a></td>"
oldtasks = ""
tasks = []
newtasks = []
title = []
start = []
end = []
table1 = "<tbody class=\"bb0\">"
table2 = "</tbody>"
html1 = "<html>\n<head>\n<meta locale=\"utf-8\">\n<style>\ntable, th, td {\nborder: 1px solid black;\nborder-collapse: collapse;\npadding: 8px;\n}\n</style>\n</head>\n<body>\n<table>\n<tbody>"
html2 = "</tbody>\n</table>\n</body>\n</html>"
taskname1 = "<h1>Details zu "
taskname2 = "</h1>"
taskstart = "<th>Starttermin:</th>"
taskend = "<th>Abgabetermin:</th>"
fileurl = "/iserv/fs/file/exercise-dl/"
file1 = "<td><a href=\""
file2 = "\" target=\"_blank\""
date1 = "<td>"
date2 = "</td>"
headers = {'User-Agent': 'Mozilla/5.0'} #User-Agent (Browser) festlegen
credits = {'_username': username, '_password': password} #Login-Daten festlegen

#Den Nutzer benachrichtigen, wenn er nichts konfiguriert hat.
if server == "demo-iserv.de":
  print("Bitte konfiguriere dein Profil im Sourcecode dieses Programms. Andernfalls wird es nicht funktionieren!")
  sys.exit(1) #Programm mit Fehlercode verlassen

#Verbindung aufbauen
print("Verbinde zu IServ...")
session = requests.Session()
session.post('https://' + server + '/iserv/login_check', headers=headers, data=credits)

#Aufgaben herunterladen
print("Aufgabenliste wird geladen...")
html = session.get("https://" + server + "/iserv/exercise?filter[status]=" + taskfilter).text

#Aufgabenlinks extrahieren
i = int(len(html.split(url1))-1)
searchtml = html

#Extrahierte Links in Arrays indexieren
for ii in range(i):
  tasks.append(searchtml.split(url1)[1].split(url2)[0]) #Link an die Liste aller Aufgaben anfügen
  newtasks.append(searchtml.split(url1)[1].split(url2)[0]) #Link an die Liste neuer Aufgaben anfügen (Ist die Aufgabe nicht neu, wird der Link hier später wieder entfernt)
  searchtml = html.split(name)[ii+1] #Zu durchsuchendes HTML begrenzen, damit nicht der selbe Link erneut indexiert wird

#Prüfen, welche Aufgaben neu sind und welche bereits heruntergeladen wurden
try:
  oldtasks = open(datafolder + "tasks.list", "r").read()
  for i in range(len(tasks)):
    if oldtasks.find(tasks[i]) != -1:
      newtasks.remove(tasks[i])
    else:
      with open(datafolder + "tasks.list", "a") as f:
        f.write(tasks[i] + "\n")
except: #Sollte das Programm zum ersten Mal gestartet werden und es noch keine Liste geben, gibt es einen Fehler.

  #Alle Aufgaben in die Liste aller Aufgaben schreiben
  for i in range(len(tasks)):
    with open(datafolder + "tasks.list", "a") as f:
      file_object.write(tasks[i] + "\n")

  #HTML-Index schreiben
  with open(index, 'w') as f:
    f.write(html1.split("\n<tbody>")[0])
    f.write("<tr><th>Aufgabe</th><th>Start</th><th>Abgabe</th></tr>")
    f.write(html2.split("</tbody>\n")[1])

#Ausgeben, wie viele Aufgaben heruntergeladen wurden und wie viele davon neu sind
print(str(len(tasks)) + " Aufgaben gefunden, davon " + str(len(newtasks)) + " neue.")
tasks = newtasks #Für die weitere Bearbeitung nur die neuen Aufgaben berücksichtigen

#Aufgabe herunterladen
for i in range(len(tasks)):
  print("Lade Aufgabe " + str(i+1) + " von " + str(len(tasks)) + "...")
  html = session.get(tasks[i]).text

  #Daten fürs spätere Eintragen in Tabelle speichern
  title.append(html.split(taskname1)[1].split(taskname2)[0]) #Name der Aufgaben
  start.append(html.split(taskstart)[1].split(date1)[1].split(date2)[0]) #Datum, an dem die Aufgabe beginnt
  end.append(html.split(taskend)[1].split(date1)[1].split(date2)[0]) #Datum, an dem die Aufgabe endet

  #Heruntergeladene Aufgabe schreiben
  html = html.split(table1)[1].split(table2)[0]
  with open(datafolder + tasks[i].split("/")[6] + '.html', 'w') as f:
    f.write(html1)
    f.write(html)
    f.write(html2)

  #Wenn nötig, zur Aufgabe zugehörige Datei(en) herunterladen und korrekt verlinken
  while html.find(fileurl) != -1:

    #HTML neu schreiben (Tabelle fixen)
    newtml = open(datafolder + tasks[i].split("/")[6] + '.html', "r").read()
    newtml = newtml.replace("<col width=\"1%\">", "").replace("<th></th>", "")
    newtml = newtml.split("<td class=\"pl0\"><div class=\"dropdown\">")[0] + newtml.split("</div>\n</td>", 1)[1]
    with open(datafolder + tasks[i].split("/")[6] + '.html', 'w') as f:
      f.write(html1)
      f.write(newtml)
      f.write(html2)

    #Dateinamenserweiterung ermitteln
    fileend = html.split("<span class=\"text-muted\">")[0].rsplit(".", 1)[1].split("</a></td>")[0]

    #Datei herunterladen
    print("Externe Datei wird heruntergeladen... (Dies kann einen Moment dauern)")
    htmlfile = "https://" + server + html.split(file1)[1].split(file2)[0]

    #Link ändern
    data =  open(datafolder + tasks[i].split("/")[6] + '.html', 'r').readlines() #1. Datei einlesen
    for ii in range(len(data)): #2. Dinge ändern
      data[ii] = data[ii].replace(htmlfile.split(server)[1], datafolder + htmlfile.split("/")[7] + "." + fileend)
    with open(datafolder + tasks[i].split("/")[6] + '.html', 'w') as f: #3. Geänderte Datei zurückschreiben
      f.writelines(data)

    #Externe Datei speichern
    with open(datafolder + htmlfile.split("/")[7] + "." + fileend, "wb") as f:
      f.write(session.get(htmlfile).content)

    #HTML replacen (bei mehreren Dateien nicht noch einmal die selbe Datei herunterladen oder andere Dinge verwechseln).
    html = html.replace(file1, "|", 1).replace(file2, "|", 1).replace(fileurl, "|", 1).replace("<span class=\"text-muted\">", "|", 1)

#Übersicht schreiben
print("Schreibe Index...")
oldtasks = open(index, "r").read().split("</table>")[0]
with open(index, 'w') as f:
  f.write(oldtasks)
  for i in range(len(tasks)):
    f.write("<tr><th><a href=\"" + datafolder + tasks[i].split("/")[6] + ".html\">" + title[i] + "</a></th><th>" + start[i] + "</th><th>" + end[i] + "</th></tr>")
  f.write(html2.split("</tbody>\n")[1])
