from tkinter import *
import os

tfilter = ""
main = ""
datafolder = ""

def func_update_tfilter(value):
  global tfilter
  tfilter = value
  print("Taskfilter updated to: " + value)

def func_save():
  global tfilter
  global main
  global datafolder

  usrdata = open(os.path.join(datafolder, "user.data")).read()
  server = usrdata.split("server:")[1].split(";")[0]
  username = usrdata.split("username:")[1].split(";")[0]
  password = usrdata.split("password:")[1].split(";")[0]

  #Daten schreiben
  with open(os.path.join(datafolder, "user.data"), "w") as f:
    f.write("Generated by ITask Version 0.1.2\nserver:" + server + ";\nusername:" + username + ";\npassword:" + password + ";\ntaskfilter:" + tfilter + ";")
  main.destroy()

def func_main(dfolder, taskfilter):
  #Tkinter initialisieren
  global main
  global datafolder
  datafolder = dfolder

  main = Tk()
  main.title("Einstellungen")

  #Elemente hinzufügen
  Label(main, font='Helvetica 11 bold', pady=4, padx=4, text="Einstellungen").grid(row=0, column=0, columnspan=2)
  Frame(main, bg="grey", height=1, bd=0).grid(column=0, row=1, columnspan=2, sticky='ew')

  #Auswahl: taskfilter
  Label(main, text="Aufgaben:").grid(row=2, column=0, pady=4, padx=4)
  value = StringVar(main)
  value.set(taskfilter)
  taskfilter = OptionMenu(main, value, "current", "past", "all", command=func_update_tfilter)
  taskfilter.config(font='Helvetica 11')
  taskfilter.grid(row=2, column=1)

  #Button zum Speichern
  Button(master=main, text="Speichern", command=func_save).grid(row=3, column=1, pady=5, sticky='e', padx=5)
