#Import Tkinter requirements
from tkinter import Tk
from tkinter import Label
from tkinter import Frame
from tkinter import Entry
from tkinter import StringVar
from tkinter import IntVar
from tkinter import OptionMenu
from tkinter import Button
from tkinter import filedialog
from tkinter import Checkbutton
from tkinter import mainloop

#Import other requirements
from zipfile import ZipFile
from pathlib import Path
import os
import shutil
import functools
import requests

#Import internal requirements
import popup

tfilter = "current"
server = ""
username = ""
password = ""
main = ""
datafolder = ""
storepass = 1

def func_save(): #Save data
  global server
  global username
  global password
  global tfilter
  global main
  global datafolder

  if storepass == False:
    password = "[none]"
  else:
    password = password.get()

  #Write data
  with open(os.path.join(datafolder, "user.data"), "a") as f:
    f.write("Generated by ITask Version 0.1.5\nserver:" + server.get() + ";\nusername:" + username.get() + ";\npassword:" + password + ";\ntaskfilter:" + tfilter + ";")
  print("Daten wurden gespeichert!")
  main.destroy() #When the process is completed, the window is destroyed

def func_restore(): #Restore backup from .zip file
  global os
  global datafolder
  global main

  #Re-create datafolder
  shutil.rmtree(datafolder)
  os.mkdir(datafolder)

  #Unzip Backup
  with ZipFile(filedialog.askopenfilename(initialdir = Path.home(), title = "Datei wählen", filetypes = (("Zip-Dateien", "*.zip"), ("Alle Dateien", "*.*"))),'r') as zip:
    zip.extractall(datafolder)
  main.destroy() #When the process is completed, the window is destroyed

def func_update_tfilter(value): #Update the 'taskfilter' variable to the value selected in the dropdown
  global tfilter
  tfilter = value

def func_update_checkbox(value):
  global storepass
  global password
  storepass = bool(value.get())
  if storepass:
    password['state'] = "normal"
  else:
    password['state'] = "disabled"

def func_main(df):
  global server
  global username
  global password
  global main
  global datafolder
  datafolder = df

  print("Einrichtungsassistent wird geöffnet")
  main = Tk()
  main.title("Einrichtung")

  #Add text elements
  Label(main, font='Helvetica 11 bold', pady=4, padx=4, text="Willkommen bei ITask!").grid(row=0, column=0, columnspan=3)
  Label(main, text="Domain:").grid(row=1, column=0)
  Label(main, text="Benutzername:").grid(row=2, column=0)
  Label(main, text="Passwort:").grid(row=3, column=0)
  Label(main, text="Aufgaben:").grid(row=4, column=0)

  #Add text fields
  server = Entry(main)
  username = Entry(main)
  password = Entry(main, show="*")
  server.grid(row=1, column=1)
  username.grid(row=2, column=1)
  password.grid(row=3, column=1)

  #Add popup selector and checkbox
  v1 = StringVar(main)
  v1.set("current")
  taskfilter = OptionMenu(main, v1, "current", "past", "all", command=func_update_tfilter)
  taskfilter.config(font='Helvetica 11')
  taskfilter.grid(row=4, column=1)

  #Add checkbox
  v2 = IntVar(value=1)
  checkbox = Checkbutton(main, text='Passwort speichern', variable=v2, onvalue=1, offvalue=0, command=functools.partial(func_update_checkbox, v2))
  checkbox.grid(row=5, column=1)

  #Add help buttons
  Button(main, text="?", command=functools.partial(popup.func_main, 1)).grid(row=1, column=2)
  Button(main, text="?", command=functools.partial(popup.func_main, 2)).grid(row=2, column=2)
  Button(main, text="?", command=functools.partial(popup.func_main, 3)).grid(row=3, column=2)
  Button(main, text="?", command=functools.partial(popup.func_main, 4)).grid(row=4, column=2)

  #Configure submit and restore buttons
  submit = Button(main, text="Speichern", command=func_save)
  submit.grid(row=5, column=0, pady=3)
  Frame(main, bg="grey", height=1, bd=0).grid(column=0, row=6, columnspan=3, sticky='ew')
  restore = Button(main, text="Backup laden", command=func_restore)
  restore.grid(row=7, column=0, columnspan=3, pady=3)

  mainloop()
